export const SOURCE_CONTRACT_ABI = [
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'token', type: 'address' },
          {
            internalType: 'address',
            name: 'tokenDestination',
            type: 'address',
          },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'address', name: 'user', type: 'address' },
        ],
        internalType: 'struct Source.BorrowData',
        name: 'borrowData',
        type: 'tuple',
      },
      {
        internalType: 'uint64',
        name: '_destinationChainSelector',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: '_calledChainSelector',
        type: 'uint64',
      },
      { internalType: 'address', name: '_receiver', type: 'address' },
      {
        internalType: 'address',
        name: '_calledReceiver',
        type: 'address',
      },
      { internalType: 'uint256', name: '_gasFeeAmount', type: 'uint256' },
    ],
    name: 'borrowTokenMessage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_router', type: 'address' },
      { internalType: 'address', name: '_link', type: 'address' },
      { internalType: 'address', name: '_swapRouter02', type: 'address' },
      { internalType: 'address', name: '_usdcToken', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'SOURCE__addressIsDiffFromSender', type: 'error' },
  { inputs: [], name: 'SOURCE__amountIsZero', type: 'error' },
  { inputs: [], name: 'SOURCE__failedToBorrow', type: 'error' },
  { inputs: [], name: 'SOURCE__failedToReceiveToken', type: 'error' },
  { inputs: [], name: 'SOURCE__failedToRemoveLend', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'value', type: 'uint256' },
    ],
    name: 'SOURCE__failedToWithdrawEth',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'faultyCaller', type: 'address' },
    ],
    name: 'SOURCE__onlyOwnerCanCall',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'faultyTokenAddr',
        type: 'address',
      },
    ],
    name: 'SOURCE__tokenNotSupported',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'messageId',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'destinationChainSelector',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
    ],
    name: 'BorrowMessageSent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'BorrowedToken',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'messageId',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'destinationChainSelector',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'gasFeeAmount',
        type: 'uint256',
      },
    ],
    name: 'LendMessageSent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'messageId',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'destinationChainSelector',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
    ],
    name: 'RePayMessageSent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'messageId',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'destinationChainSelector',
        type: 'uint64',
      },
    ],
    name: 'RemoveLendMessageSent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'RemovedLend',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'allowedToken',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'borrowToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },

  {
    inputs: [],
    name: 'getLinkAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getOwnerAddr',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRouterAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSwapRouterAddr',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'getTokenAmountMessage',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        internalType: 'struct Client.EVMTokenAmount[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getUsdcAddr',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_token', type: 'address' }],
    name: 'isTokenSupported',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'address', name: 'usdcToken', type: 'address' },
          {
            internalType: 'address',
            name: 'usdctokenDestination',
            type: 'address',
          },
          { internalType: 'address', name: 'user', type: 'address' },
        ],
        internalType: 'struct Source.LendData',
        name: 'lendData',
        type: 'tuple',
      },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      {
        internalType: 'uint64',
        name: '_destinationChainSelector',
        type: 'uint64',
      },
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_gasFeeAmount', type: 'uint256' },
    ],
    name: 'lendToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
      {
        internalType: 'address',
        name: '_tokenDestination',
        type: 'address',
      },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      {
        internalType: 'uint64',
        name: '_destinationChainSelector',
        type: 'uint64',
      },
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_gasFeeAmount', type: 'uint256' },
    ],
    name: 'rePayBorrow',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'removeLend',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_tokenAddress', type: 'address' },
      { internalType: 'bool', name: '_allowed', type: 'bool' },
    ],
    name: 'setAllowedToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOnwer', type: 'address' }],
    name: 'setNewOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newAddress', type: 'address' }],
    name: 'setUsdc',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
      {
        internalType: 'address',
        name: '_tokenDestination',
        type: 'address',
      },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      {
        internalType: 'uint64',
        name: '_destinationChainSelector',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: '_calledChainSelector',
        type: 'uint64',
      },
      { internalType: 'address', name: '_receiver', type: 'address' },
      {
        internalType: 'address',
        name: '_calledReceiver',
        type: 'address',
      },
      { internalType: 'uint256', name: '_gasFeeAmount', type: 'uint256' },
    ],
    name: 'withdrawMessage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'withdrawToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
];
